# Override some options for Docker Compose
#
# In a local test environment, the docker-compose.override.yml will
# also be loaded, and override some settings of the docker-compose.yml file.

version: "3.7"
services:
  adminer:
    ports:
      - "8080:8080"
